# Generated by Django 4.0.5 on 2022-06-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recieveSMS', '0002_rename_text_smsstorage_full_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='sendSMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('phoneNo', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'storing sent message',
                'verbose_name_plural': 'storing sent messages',
            },
        ),
        migrations.AlterModelOptions(
            name='smsstorage',
            options={'verbose_name': 'storing received message', 'verbose_name_plural': 'storing received messages'},
        ),
    ]
