# Generated by Django 4.0.5 on 2022-06-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recieveSMS', '0003_sendsms_alter_smsstorage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendsms',
            name='error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sendsms',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='smsstorage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
