# Generated by Django 4.0.5 on 2022-06-22 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recieveSMS', '0004_sendsms_error_alter_sendsms_createdat_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sendsms',
            options={'verbose_name': 'Send message', 'verbose_name_plural': 'Send messages'},
        ),
    ]
