# Generated by Django 4.0.5 on 2022-06-22 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='formatedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('cnic', models.CharField(max_length=300)),
                ('contactNumber', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=300)),
                ('data', models.JSONField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=300, null=True)),
                ('dataSource', models.CharField(choices=[('P', 'Partners'), ('O', 'Other')], default='O', max_length=300)),
                ('notes', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
